Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end

  config.vm.define "splunk-forwarder1" do |node|
    node.vm.hostname = "forwarder1"
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.provision "shell", path: "provision/splunk-forwarder.sh"
  end

  config.vm.define "splunk-forwarder2" do |node|
    node.vm.hostname = "forwarder2"
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.provision "shell", path: "provision/splunk-forwarder.sh"
  end

end