NAME="splunk-enterprise"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end

  config.vm.define "#{NAME}-node1" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.provision "shell", path: "splunk.sh"
    node.vm.network "forwarded_port", host: 20001, guest: 8000
  end

end