Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end

  config.vm.define "splunk-server" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.provision "shell", path: "provision/splunk-server.sh"

    node.vm.network "private_network", ip: "172.28.128.10"

  end

  config.vm.define "splunk-forwarder1" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.provision "shell", path: "provision/splunk-forwarder.sh"
  end

end